config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  resources :trips do
  resources :reservations
  end
  
  resources :locations do
  resources :reservations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
has_many :reservations, dependent: :destroy
has_many :trips, through: :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :trip
  belongs_to :location
end

app/models/reversation.rb
class Reversation < ApplicationRecord
  belongs_to :trip
  belongs_to :location
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :locations, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to @location
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private
  def set_location
    @location = Location.find(params[:id])
  end
  def location_params
    params.require(:location).permit(:loc_name, :loc_type, :main_activity)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_trip 
  before_action :set_location
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = @trip.reservations
  end

  def show
  end

  def new
    @reservation = @trip.reservations.new
  end

def create
  @reservation = @trip.reservation.new(reservation_params)
  if @reservation.save
    redirect_to trip_reservations_path(@trip)
  else
    render :new
  end
end

  def edit
  end

  def update
    if @reservation.update(reservatio_params)
    redirect_to trip_reservations_path(trip_id)
    else
      render :edit
    end
  end

  def destroy
    @reservation = @trip.reservations.find(params[:id])
    @reservation.destroy
    redirect_to trip_reservations_path(@trip)
  end

  private
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
  def reservation_params
    params.require(:reservation).permit()
  end
  def set_trip
    @trip = Trip.find(params[:trip_id])
  end
  def set_location
    @location = Location.find(params[:location_id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

   def index
    @trips = Trip.all
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end
  def trip_params
    params.require(:trip).permit(:trip_name, :first_name, :last_name, :party_size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_navbar.html.erb
  <a><%= link_to  "Home", root_path %></a>
  <a><%= link_to "Your Reservations" Reservations_path %></a>
  <a><%= link_to "Your Locations", locations_path %></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link ="stylesheet" href ="trips.scss">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <nav>
  <w2>
    <%= render 'layouts/navbar' %>
  </w2>
  </nav>

<body>

    <%= yield %>
  </body>

</html>

app/views/locations/edit.html.erb
<h1>Edit Locations</h1>

<%= form_for @location do |f| %>

  <%= f.label :location_name %>
  <%= f.text_field :loc_name, require: true, placeholder: 'Location Name' %>

  <%= f.label :location_type %>
  <%= f.text_field :loc_type, require: true, placeholder: 'Location Type'%>

  <%= f.label :main_activity %>
  <%= f.text_field :main_activity, require: true, placeholder: 'Main Attractions/Activities' %>

  <%= f.submit %>

  <% end %>

app/views/locations/index.html.erb
<h1>Locations List</h1>

<%= link_to 'Add Location', new_location_path %>
<br />
<h2><%= @locations.length <= 0 ? "No Locations" : "" %></h2> 

  <% @locations.each do |location| %>
  <ul>
    <li>
        <%= link_to location.loc_name, location_path(location) %>
    </li>
  </ul>  
<% end %>

app/views/locations/new.html.erb
<h1>Add Location</h1>

<%= form_for @location do |f| %>

  <%= f.label :location_name %>
  <%= f.text_field :loc_name, require: true, placeholder: 'Location Name'%>

  <%= f.label :location_type %>
  <%= f.text_field :loc_type, require: true, placeholder: 'Location Type' %>

  <%= f.label :main_activity %>
  <%= f.text_field :main_activity, require: true, placeholder: 'Main Attractions/Activities' %>

  <%= f.submit %>




<% end %>

app/views/locations/show.html.erb
<h1><%= @location.loc_name.capitalize %></h1>
<br/>
<h2> <%= @location.loc_type %> </h2>
<br/>
<h2> <%= @location.main_activity %> </h2>

<%= link_to 'Edit Location', edit_location_path(@location) %>
<%= link_to 'Delete Location', location_path(@location), method: :delete %>
<br/>
<br/>
<%= link_to 'Back',locations_path() %>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<hi><%= @location.name %>: Reservations</hi>
<%= link_to 'Add Reservation', new_reservation_path(@location)%>
<hr />

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/trips/_form.html.erb
<%= form_with(model: @trip, local: true, class: 'ui form') do |f| %>
  <div class='field'>
    <%= f.label :trip_name %>
    <%= f.text_field :trip_name, required: true, placeholder: 'Trip Name' %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, require: true, placeholder: 'First Name' %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, require: true, placeholder: 'Last Name' %>

    <%= f.label :party_size %>
    <%= f.text_field :party_size, require: true, placeholder: 'Party Size'%>

  </div>
  <div class = bre>
  <%= f.submit nil, class: "ui secondary button" %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Edit Trips</h1>
<%= render partial: 'form' %>

app/views/trips/index.html.erb
<head> 
<link ="stylesheet" href ="trips.scss">
</head>

<h1 class = "header" ><%= @trip %></h1>
<div class="container">
<h1>Trip List</h1>
<div class= create_trip> <%= link_to 'Create Trip', new_trip_path(@trip) %></div>
<ul>
  <% @trips.each do |trip| %>
    <li>
      <%= link_to trip.trip_name, trip_path(trip) %>
    </li>
  <% end %>
</ul>

app/views/trips/new.html.erb
<h1 class='ui header'>New Trip</h1>
<%= render "form" %>
<%= link_to "Back", root_path %>

app/views/trips/show.html.erb
<h1> <%= @trip.trip_name %> </h1>

<h2> Traveler's Name: <%= @trip.first_name %> </h2>

<h2> Party Size: <%= @trip.party_size %> </h2>

<p>what do you want to do</p>
<%= link_to 'Edit Trip', edit_trip_path(@trip) %>
<br />
<%= link_to 'Delete Trip', @trip, method: :delete %>
<br />
<%= link_to 'View locations', locations_path %>